service:
  name: desafioserverlessignite

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Actions:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  createTodos: 
    handler: src/functions/createTodos.handle
    events:
      - http:
          path: /todos/{user_id}
          method: POST
          cors: true
  listTodos: 
    handler: src/functions/listTodos.handle
    events:
      - http:
          path: /todos/{user_id}
          method: GET
          cors: true

resources:
  Resources:
    dbTodosServerless:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tb_todos
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: id
            KeyType: HASH